# Application of Machine Learning Methods to Analysis of Cyber-Sport Events
## Dmitry Savostyanov, 131
## TrueSkill by Teams

### Role:
###### 1 - Carry
###### 2 - Mid
###### 3 - Hard-lane
###### 4 - Semi-support
###### 5 - Full-support

### Взаимодействие с Dotabuff:
###### Информация об игроке: https://www.dotabuff.com/esports/players/<'account_id'>

###### Информация о матче: https://www.dotabuff.com/matches/<'match_id'>

###### Информация о команде: https://www.dotabuff.com/esports/teams/<'team_id'>

In [2]:
import trueskill as ts

import urllib2
import json
import random
import datetime

import math 
import pandas as pd 
import numpy as np 
import sklearn 
import matplotlib.pyplot as plt 
 
%matplotlib inline
plt.style.use('ggplot')

# Data Import

In [3]:
sdf_1 = pd.read_csv('ScoresByRole_1.csv',
                                sep = ';',
                                index_col = 0,
                               dtype = {
                                   '': 'str',
                                   'account_id' : 'str',
                                   'match_id' : 'str', 
                                   'team_id' : 'str', 
                                   'role' : 'str',
                                   'datetime' : 'str', 
                                   'win' : 'bool', 
                                   'win_prob' : 'float64', 
                                   'prediction' : 'bool',
                                   'isCorrect' : 'bool'
                               })
sdf_2 = pd.read_csv('ScoresByRole_2.csv',
                                sep = ';',
                                index_col = 0,
                               dtype = {
                                   '': 'str',
                                   'account_id' : 'str',
                                   'match_id' : 'str', 
                                   'team_id' : 'str', 
                                   'role' : 'str',
                                   'datetime' : 'str', 
                                   'win' : 'bool', 
                                   'win_prob' : 'float64', 
                                   'prediction' : 'bool',
                                   'isCorrect' : 'bool'
                               })
sdf_3 = pd.read_csv('ScoresByRole_3.csv',
                                sep = ';',
                                index_col = 0,
                               dtype = {
                                   '': 'str',
                                   'account_id' : 'str',
                                   'match_id' : 'str', 
                                   'team_id' : 'str', 
                                   'role' : 'str',
                                   'datetime' : 'str', 
                                   'win' : 'bool', 
                                   'win_prob' : 'float64', 
                                   'prediction' : 'bool',
                                   'isCorrect' : 'bool'
                               })
sdf_4 = pd.read_csv('ScoresByRole_4.csv',
                                sep = ';',
                                index_col = 0,
                               dtype = {
                                   '': 'str',
                                   'account_id' : 'str',
                                   'match_id' : 'str', 
                                   'team_id' : 'str', 
                                   'role' : 'str',
                                   'datetime' : 'str', 
                                   'win' : 'bool', 
                                   'win_prob' : 'float64', 
                                   'prediction' : 'bool',
                                   'isCorrect' : 'bool'
                               })
sdf_5 = pd.read_csv('ScoresByRole_5.csv',
                                sep = ';',
                                index_col = 0,
                               dtype = {
                                   '': 'str',
                                   'account_id' : 'str',
                                   'match_id' : 'str', 
                                   'team_id' : 'str', 
                                   'role' : 'str',
                                   'datetime' : 'str', 
                                   'win' : 'bool', 
                                   'win_prob' : 'float64', 
                                   'prediction' : 'bool',
                                   'isCorrect' : 'bool'
                               })

In [4]:
sdf = pd.concat([sdf_1, sdf_2, sdf_3, sdf_4, sdf_5])

In [5]:
matches = sdf.sort_values(by = ['match_id', 'team_id', 'role'], ascending = False)

In [6]:
# matches

# Cumulative Score (match_id + team_id)

In [7]:
cumprob = matches.groupby(['match_id', 'team_id'], as_index=False)['win_prob'].sum()
cumprob.rename(columns = {'win_prob' : 'cumulative_prob'}, inplace = True)

In [8]:
cumprob.sort_values(by = ['match_id', 'cumulative_prob'], ascending = False, inplace = True)
# cumprob

In [9]:
matches = pd.merge(matches, cumprob, on=['match_id', 'team_id'], how='inner')
matches.rename(columns = {'win_prob_x' : 'win_prob', 'win_prob_y' : 'cumulative_prob'}, inplace = True)

In [10]:
matches['win_contribution'] = matches['win_prob'] / matches['cumulative_prob']

In [11]:
# matches.sort_values(by = ['match_id', 'team_id', 'cumulative_prob', 'win_contribution'], ascending = False)

In [12]:
matchesFreq = matches.groupby(['match_id'])['match_id'].count()

In [13]:
len(matchesFreq)

560

#### Избавимся от матчей, которые представлены менее чем 10 записями

In [14]:
fullMatches = matchesFreq[matchesFreq == 10]
len(fullMatches)

207

In [15]:
isFull = np.in1d(matches['match_id'], fullMatches.index.values)

In [16]:
len(isFull)

4930

In [17]:
matches['isFull'] = isFull

In [18]:
sMatches = matches[matches['isFull'] == True]

# Финальная таблица
## Описание полей:
account_id - Идентификатор игрока

match_id - Идентификатор матча

team_id - Идентификатор команды

role - Исполняемая роль (Описание См. Выше)

datetime - Дата окончания матча

win - Идентификатор победы (Целевая переменная)

win_prob - Предсказанная вероятность победы на основе информации по игроку данной роли

prediction - Предсказание со стандартным порогом отсечения (True if win_prob >= 0.5)

isCorrect - Флаг совпадения предсказания с реальностью

cumulative_prob - Сумма вероятностей победы по команде в матче

win_contribution - Вклад игрока данной роли в победу (win_prob / cumulative_prob)

isFull - Флаг того, что для данного match_id в таблице имеется ровно 10 записей (по 5 на команду)

In [19]:
sMatches.sort_values(by = ['match_id', 'team_id', 'cumulative_prob', 'win_contribution'], ascending = False, inplace = True)

C:\Program Files (x86)\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [20]:
matches = sMatches

In [21]:
matches

,account_id,match_id,team_id,role,datetime,win,win_prob,prediction,isCorrect,cumulative_prob,win_contribution,isFull
3,311360822,3149572447,2586976,2.0,30.04.2017 22:09:06,True,0.998942,True,True,3.151250,0.316999,True
0,94155156,3149572447,2586976,5.0,30.04.2017 22:09:06,True,0.689940,True,True,3.151250,0.218942,True
1,26771994,3149572447,2586976,4.0,30.04.2017 22:09:06,True,0.676170,True,True,3.151250,0.214572,True
2,41231571,3149572447,2586976,3.0,30.04.2017 22:09:06,True,0.577774,True,True,3.151250,0.183348,True
4,19672354,3149572447,2586976,1.0,30.04.2017 22:09:06,True,0.208424,False,False,3.151250,0.066140,True
9,132851371,3149572447,1883502,1.0,30.04.2017 22:09:06,False,0.841920,True,False,1.934337,0.435250,True
5,134556694,3149572447,1883502,5.0,30.04.2017 22:09:06,False,0.662124,True,False,1.934337,0.342300,True
8,106573901,3149572447,1883502,2.0,30.04.2017 22:09:06,False,0.218387,False,True,1.934337,0.112900,True
6,106809101,3149572447,1883502,4.0,30.04.2017 22:09:06,False,0.148795,False,True,1.934337,0.076923,True
7,92423451,3149572447,1883502,3.0,30.04.2017 22:09:06,False,0.063111,False,True,1.934337,0.032627,True
21,41231571,3149353238,2586976,3.0,30.04.2017 19:46:31,False,0.197367,False,True,0.460987,0.428140,True
22,311360822,3149353238,2586976,2.0,30.04.2017 19:46:31,False,0.101919,False,True,0.460987,0.221089,True
20,26771994,3149353238,2586976,4.0,30.04.2017 19:46:31,False,0.092605,False,True,0.460987,0.200884,True
19,94155156,3149353238,2586976,5.0,30.04.2017 19:46:31,False,0.065025,False,True,0.460987,0.141056,True
23,19672354,3149353238,2586976,1.0,30.04.2017 19:46:31,False,0.004071,False,True,0.460987,0.008831,True
28,132851371,3149353238,1883502,1.0,30.04.2017 19:46:31,True,0.999401,True,True,4.790750,0.208610,True
27,106573901,3149353238,1883502,2.0,30.04.2017 19:46:31,True,0.994752,True,True,4.790750,0.207640,True
25,106809101,3149353238,1883502,4.0,30.04.2017 19:46:31,True,0.986507,True,True,4.790750,0.205919,True
24,134556694,3149353238,1883502,5.0,30.04.2017 19:46:31,True,0.907979,True,True,4.790750,0.189528,True
26,92423451,3149353238,1883502,3.0,30.04.2017 19:46:31,True,0.902111,True,True,4.790750,0.188303,True
47,25907144,3148721353,39,5.0,30.04.2017 14:32:58,False,0.788840,True,False,2.258431,0.349287,True
48,73562326,3148721353,39,4.0,30.04.2017 14:32:58,False,0.760400,True,False,2.258431,0.336694,True
50,111620041,3148721353,39,2.0,30.04.2017 14:32:58,False,0.602501,True,False,2.258431,0.266779,True
49,87276347,3148721353,39,3.0,30.04.2017 14:32:58,False,0.087892,False,True,2.258431,0.038917,True
51,86745912,3148721353,39,1.0,30.04.2017 14:32:58,False,0.018797,False,True,2.258431,0.008323,True
55,311360822,3148721353,2586976,2.0,30.04.2017 14:32:58,True,0.990333,True,True,3.503708,0.282653,True
53,26771994,3148721353,2586976,4.0,30.04.2017 14:32:58,True,0.929020,True,True,3.503708,0.265153,True
52,94155156,3148721353,2586976,5.0,30.04.2017 14:32:58,True,0.800064,True,True,3.503708,0.228348,True
54,41231571,3148721353,2586976,3.0,30.04.2017 14:32:58,True,0.509387,True,True,3.503708,0.145385,True
56,19672354,3148721353,2586976,1.0,30.04.2017 14:32:58,True,0.274904,False,False,3.503708,0.078461,True
...,...,...,...,...,...,...,...,...,...,...,...,...
4882,25907144,3033099678,39,5.0,04.03.2017 00:12:18,True,0.913804,True,True,4.430335,0.206261,True
4886,86745912,3033099678,39,1.0,04.03.2017 00:12:18,True,0.908030,True,True,4.430335,0.204957,True
4885,111620041,3033099678,39,2.0,04.03.2017 00:12:18,True,0.897126,True,True,4.430335,0.202496,True
4884,87276347,3033099678,39,3.0,04.03.2017 00:12:18,True,0.893853,True,True,4.430335,0.201757,True
4883,73562326,3033099678,39,4.0,04.03.2017 00:12:18,True,0.817522,True,True,4.430335,0.184528,True
4887,115141430,3033099678,3333433,2.0,04.03.2017 00:12:18,False,0.554352,True,False,0.554352,1.000000,True
4890,86811043,3033099678,3,3.0,04.03.2017 00:12:18,False,0.166942,False,True,0.285430,0.584880,True
4889,50828662,3033099678,3,4.0,04.03.2017 00:12:18,False,0.071127,False,True,0.285430,0.249193,True
4888,49317728,3033099678,3,5.0,04.03.2017 00:12:18,False,0.035825,False,True,0.285430,0.125514,True
4891,84429681,3033099678,3,1.0,04.03.2017 00:12:18,False,0.011535,False,True,0.285430,0.040413,True
4895,111620041,3033038349,39,2.0,03.03.2017 23:21:13,True,0.952900,True,True,4.078116,0.233662,True
4894,87276347,3033038349,39,3.0,03.03.2017 23:21:13,True,0.938954,True,True,4.078116,0.230242,True
4893,73562326,3033038349,39,4.0,03.03.2017 23:21:13,True,0.814325,True,True,4.078116,0.199682,True
4896,86745912,3033038349,39,1.0,03.03.2017 23:21:13,True,0.702957,True,True,4.078116,0.172373,True
4892,25907144,3033038349,39,5.0,03.03.2017 23:21:13,True,0.668981,True,True,4.078116,0.164042,True
4897,115141430,3033038349,3333433,2.0,03.03.2017 23:21:13,False,0.019122,False,True,0.019122,1.000000,True
4900,86811043,3033038349,3,3.0,03.03.2017 23:21:13,False,0.032753,False,True,0.079428,0.412365,True
4899,50828662,3033038349,3,4.0,03.03.2017 23:21:13,False,0.023079,False,True,0.079428,0.290563,True
4898,49317728,3033038349,3,5.0,03.03.2017 23:21:13,False,0.014318,False,True,0.079428,0.180260,True
4901,84429681,3033038349,3,1.0,03.03.2017 23:21:13,False,0.009278,False,True,0.079428,0.116813,True
4904,87276347,3032935500,39,3.0,03.03.2017 22:06:47,False,0.976821,True,False,1.557963,0.626986,True
4902,25907144,3032935500,39,5.0,03.03.2017 22:06:47,False,0.267586,False,True,1.557963,0.171753,True
4906,86745912,3032935500,39,1.0,03.03.2017 22:06:47,False,0.205022,False,True,1.557963,0.131596,True
4905,111620041,3032935500,39,2.0,03.03.2017 22:06:47,False,0.095572,False,True,1.557963,0.061344,True
4903,73562326,3032935500,39,4.0,03.03.2017 22:06:47,False,0.012964,False,True,1.557963,0.008321,True
4907,115141430,3032935500,3333433,2.0,03.03.2017 22:06:47,True,0.998973,True,True,0.998973,1.000000,True
4910,86811043,3032935500,3,3.0,03.03.2017 22:06:47,True,0.998483,True,True,3.821084,0.261309,True
4911,84429681,3032935500,3,1.0,03.03.2017 22:06:47,True,0.985899,True,True,3.821084,0.258015,True
4909,50828662,3032935500,3,4.0,03.03.2017 22:06:47,True,0.924733,True,True,3.821084,0.242008,True
4908,49317728,3032935500,3,5.0,03.03.2017 22:06:47,True,0.911969,True,True,3.821084,0.238668,True

Инициализация рейтингов TrueSkill

In [140]:
trs = {}
for i in range(0, matches.shape[0]):
    trs[matches['team_id_x'].iloc[i]] = ts.Rating()
    trs[matches['team_id_y'].iloc[i]] = ts.Rating()